-- Write your query below and then click "Run Query" to execute it. To save multiple queries, click the "+" icon on the left.
SELECT EMPLOYEE.EMP_NUM, EMP_LNAME, ROUND(SUM(ASSIGN_HOURS), 1) AS SumOfASSIGN_HOURS, ROUND(SUM(ASSIGN_CHARGE), 2) AS SumOfASSIGN_CHARGE
FROM ASSIGNMENT
INNER JOIN EMPLOYEE 
ON ASSIGNMENT.EMP_NUM = EMPLOYEE.EMP_NUM
GROUP BY EMP_NUM
