SELECT CUS_CODE, INVOICE.INV_NUMBER, INV_DATE, P_DESCRIPT, LINE_UNITS, LINE_PRICE
FROM INVOICE
INNER JOIN LINE
ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
INNER JOIN PRODUCT
ON PRODUCT.P_CODE = LINE.P_CODE
ORDER BY CUS_CODE, INV_NUMBER, P_DESCRIPT
