SELECT CUS_CODE, INVOICE.INV_NUMBER, P_DESCRIPT, LINE_UNITS As 'Units Bought', LINE_PRICE As 'Unit Price', ROUND(LINE_UNITS*LINE_PRICE, 2) As Subtotal
FROM INVOICE
INNER JOIN LINE
ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
INNER JOIN PRODUCT
ON LINE.P_CODE = PRODUCT.P_CODE
ORDER BY CUS_CODE, INV_NUMBER, P_DESCRIPT
